### ISSUE TITLE
The plugin doesn't works

### ISSUE THREAD

**Issue by temuccio** [MoonshineSG/OctoPrint-MultiColors#1]
Hello, 
I have installed the plugin.
I see the tab multicolor but if I click on it the windows doesn't show.
Do you can help me?
I use octoprint version 1.2.13.

**Comment by temuccio** [comment]
I have see the console log and the error is this:
`Uncaught ReferenceError: OctoPrint is not defined packed_app.js?e311a25d:7382`

**Comment by MoonshineSG** [comment]
it seams that I made a mistake and the plugin requires some functions that are available only in "dev" branch... 
I'll try to find a workaround...

**Comment by MoonshineSG** [comment]
1.0.1 should fix the problem

**Comment by temuccio** [comment]
Now it's works. 
Thanks
