### ISSUE TITLE
Update regex to support multi-line and use match in replacement

### ISSUE THREAD

**Issue by jewzaam** [MoonshineSG/OctoPrint-MultiColors#11]
I use Slic3r and layer comments are on the line for moving to next layer's first position.  To do layer change, need to be able to inject gcode before this line.

Example
```
G1 E574.34601 F1800.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.680 F9600.000 ; move to next layer (6)
```

Current plugin functionality:
```
G1 E574.34601 F1800.00000 ; retract
G92 E0 ; reset extrusion distance
G1 Z1.680 F9600.000 ; move to next layer (6)
G91            ;Set Relative Mode
G1 E-5.000000 F500   ;Retract 5mm
G1 Z15 F300         ;move Z up 15mm
G90            ;Set Absolute Mode
G1 X20 Y20 F9000      ;Move to hold position
G91            ;Set Relative Mode
G1 E-40 F500      ;Retract 40mm
M0            ;Idle Hold
G90            ;Set Absolute Mode
G1 F5000         ;Set speed limits
G28 X0 Y0         ;Home X Y
M82            ;Set extruder to Absolute Mode
G92 E0         ;Set Extruder to 0
```

Desired plugin functionality:
```
;G1 E574.34601 F1800.00000 ; retract
;G92 E0 ; reset extrusion distance
;Pause Code
G91            ;Set Relative Mode
G1 E-5.000000 F500   ;Retract 5mm
G1 Z15 F300         ;move Z up 15mm
G90            ;Set Absolute Mode
G1 X20 Y20 F9000      ;Move to hold position
G91            ;Set Relative Mode
G1 E-40 F500      ;Retract 40mm
M0            ;Idle Hold
G90            ;Set Absolute Mode
G1 F5000         ;Set speed limits
G28 X0 Y0         ;Home X Y
M82            ;Set extruder to Absolute Mode
G1 E574.34601 F1800.00000 ; retract
G92 E0         ;Set Extruder to 0
; unpaused
G1 Z1.680 F9600.000 ; move to next layer (6)
```
Note the retract and extrusion reset are commented out (could be deleted) and the retract is moved to just before last extrusion command.

**Comment by jewzaam** [comment]
Possibly just a lack of documentation and personal understanding of how regex works in python.  Digging into things and will post a PR with some doc updates if that's the case.

**Comment by MoonshineSG** [comment]
It does support multi line for the replacement.  And I am not sure why the "before" option does not work...

**Comment by jewzaam** [comment]
I don't see but the regex and gcode in the plugin.  But assuming the regex works the way I think it should, it can do what I need already.  Have a print in progress but will play around after that.

**Comment by MoonshineSG** [comment]
I'm sure that by playing with the inserted GCODE you can make it work even if it's inserted after the matching line. 
Let me know if you need any help.

**Comment by jewzaam** [comment]
True, replaying a few things got it working (at least looks good in an editor).  Testing will be of the gcode, not the plugin.  Thanks!

**Comment by jewzaam** [comment]
FWIW, my settings: https://gist.github.com/jewzaam/9f43dd0607ffb39a23967366121d1174
