### ISSUE TITLE
doesn't work with cura gcode

### ISSUE THREAD

**Issue by albebert** [MoonshineSG/OctoPrint-MultiColors#15]
Hello, 

i use cura in repetier-host for slicing.

layer in gcode are : 

;LAYER:10

so i try to user this regexp : 
.*LAYER:{layer}.*

but no luck :/

can you help me ?

**Comment by MoonshineSG** [comment]
try `;LAYER:{layer}`

**Comment by albebert** [comment]
same thing :(

**Comment by MoonshineSG** [comment]
Send me a bigger sample

**Comment by albebert** [comment]
http://dl.free.fr/ry7Xc8hHn

**Comment by MoonshineSG** [comment]
the `;LAYER:{layer}` should work. i tested against your file and it's a match... 

see https://regex101.com/r/Rj4ffA/1

the `(`, `$)` are added by the plugin (https://github.com/MoonshineSG/OctoPrint-MultiColors/blob/master/octoprint_multi_colors/__init__.py#L74)


Can you paste the logs from your OctoPrint ?

**Comment by albebert** [comment]
with log ?

**Comment by MoonshineSG** [comment]
Octoprint logs? Under the settings or via SSH?

**Comment by albebert** [comment]
/home/pi/.octoprint/logs/octoprint.log i only have this : 
2017-07-20 15:43:58,031 - octoprint.plugins.multi_colors - INFO - on_api_command called: 'process' / '{u'layers': u'5', u'gcode': u'M117 Change filament\nM0', u'find_string': u';LAYER:{layer}', u'command': u'process', u'file': u'20mm_calibration_cube.gcode'}'
2017-07-20 15:43:58,042 - octoprint.plugins.multi_colors - INFO - File to modify '/home/pi/.octoprint/uploads/20mm_calibration_cube.gcode'
2017-07-20 15:43:58,086 - octoprint.plugins.multi_colors - INFO - Trying to insert multi color code for layer '5'...

the "original" regexp from plugin install work on an S3D gcode file, so the plugins work. 

but seem to have a problem with the cura regexp

**Comment by MoonshineSG** [comment]
anything else after the line  "Trying to insert multi color code for layer '5'..." ?

**Comment by MoonshineSG** [comment]
and what is the error you get ?

**Comment by MoonshineSG** [comment]
`;LAYER:{layer}\r` will work. Sliced  on Windows by any chance ?

**Comment by MoonshineSG** [comment]
i'm updating the plugin to handle automatically the cross platform line terminator

**Comment by MoonshineSG** [comment]
update to 1.0.7 and use `;LAYER:{layer}`

**Comment by albebert** [comment]
Yes slicing on windows (repetier-host). 

updated, and now works ! thanks !!

you can close :)

if i can just make a comment on your plugins, it can be great if you can pickup a file from file list instead of using the loaded file. because for loading file, printed must be UP. and add a save as fonctionnaly could be great to. .

another thanks for your great job, have a good day
