### ISSUE TITLE
Injecting gcode failed

### ISSUE THREAD

**Issue by Burritobun** [MoonshineSG/OctoPrint-MultiColors#19]
I have the plugin with default config settings, after updating to 1.3.6 I have been getting the error "Injecting GCODE failed. Replaced 0 out of 2 needed." after attempting to inject into a file. I tried editing the original along with trying to duplicate the file.

**Comment by Burritobun** [comment]
Solved it by changing the "look for" to match what cura was spitting out. Cura specifies layers in this way   ";LAYER:34" so I have mine like this "LAYER:{layer}". Perhaps adding a broader search or a slicer selection button to change what the plugin looks for.

**Comment by MoonshineSG** [comment]
yes, you are supposed to configure the  regular expression  to match whatever the slicer inserts... thats the whole point of having a regular expression

**Comment by Burritobun** [comment]
My apologies. I would delete this thread if I knew how... Very new to this
whole github thing.

**Comment by MoonshineSG** [comment]
that's alright, no harm done. we all started at some point somewhere. 

Let me know if you have other questions.

**Comment by Jelenbl** [comment]
Try this as your regex statement.

.([LAYER])\w+.*([layer]).
