### ISSUE TITLE
Octoprint Analysis doesn't start

### ISSUE THREAD

**Issue by upD8R** [MoonshineSG/OctoPrint-MultiColors#22]
Hi again,

AFAIK some background analysis process is started as soon as you drag'n'drop (upload) a file to the Octoprint webpages. This results in some info, which can be accessed by a small dropdown menu in the file manager and is e.g. used for the Filament Manager plugin.

It seems, a file duplicated by Multi Colors does not trigger this analysis. Do you know how this can be achieved w/o downloading/uploading the GCode?

Thanks!

**Comment by MoonshineSG** [comment]
good catch. i'll fix this soon.

**Comment by MoonshineSG** [comment]
try the new version and let me know if it's ok

**Comment by upD8R** [comment]
Works like a charm now, thanks again for this great piece of SW!
