### ISSUE TITLE
Plugin not showing up in Octoprint?

### ISSUE THREAD

**Issue by unixb0y** [MoonshineSG/OctoPrint-MultiColors#24]
Hello,
I can't actually "find" the UI that you show in your README after installation.
Where is it supposed to be found?
I have OctoPi 0.13.0 and OctoPrint 1.3.6

**Comment by MoonshineSG** [comment]
If you’re sure the plugin is installed, maybe there are startup errors and the plugin doesn’t load properly. Check logs for errors and report back

**Comment by MoonshineSG** [comment]
Or... you have too many tabs and it’s in the right side “morel/“...” menu

**Comment by unixb0y** [comment]
Ohh yup, thanks! My screen was too narrow.
