### ISSUE TITLE
Subfolder support

### ISSUE THREAD

**Issue by upD8R** [MoonshineSG/OctoPrint-MultiColors#25]
Hi there,

it's me again. It seems files in subfolders aren't processed ("duplicate file" enabled)? I tried with 2 different files, it works in the root directory but in subfolders I don't even get a status message "... replaced".

Could you please check? Thanks very much!

Running version 1.0.13

**Comment by MoonshineSG** [comment]
fixed it. thanks for reporting it.

**Comment by IceflareTech** [comment]
In order to update do we need to update through package installer on the pi or through octoprint?

**Comment by MoonshineSG** [comment]
OctoPrint has a plugin manager that takes care of updates. You can force a check or restart OctoPrint (which will force a version check) or wait until the next scheduled version check

**Comment by upD8R** [comment]
Works, thanks again! Awesome work & support!
