### ISSUE TITLE
Insert a space in the regular expression

### ISSUE THREAD

**Issue by JoeleDixie** [MoonshineSG/OctoPrint-MultiColors#30]
Hi 
I use s3d and the gcode example is 
----------------------------------------
;G1 Z0.3 ; Raise and begin printing
G92 E0
G1 E-1.0000 F2400
G1 Z0.184 F900
; process Process1
; layer 1, Z = 0.184
T0
; tool H0.200 W0.450
; skirt
--------------------------

The regular expression is 
;layer {layer},.*

but dont work!

what should I put in the middle of ; layer and {layer},. *

Thanks!

**Comment by MoonshineSG** [comment]
just need an extra space as the second character:   `; layer {layer},.*`

**Comment by JoeleDixie** [comment]
Thanks! Now work!
