### ISSUE TITLE
Injecting GCODE failed

### ISSUE THREAD

**Issue by turuncuoglu** [MoonshineSG/OctoPrint-MultiColors#36]
I am using an Anet a8 with merlin and s3d for slicer  My g code is 
G1 X91.892 Y91.740 E18.9511
G1 X91.855 Y91.740 F2880
G1 X91.740 Y91.855 F2880
G92 E0
G1 E-10.0000 F3600
; layer 5, Z = 0.784
; inner perimeter
G1 X91.400 Y91.400 F4800
G1 Z0.784 F1002
G1 E0.4000 F3600
G92 E0
G1 X108.600 Y91.400 E0.4559 F2700
G1 X108.600 Y108.600 E0.911

![image](https://user-images.githubusercontent.com/22820400/57151798-73b14f00-6d97-11e9-8f21-b8e6803b42de.png)

I can not insert the layer.  

Thanks for your help.

**Comment by MoonshineSG** [comment]
`; layer {layer},.*?` should work... make sure the number of spaces is the same in the code and the regex

**Comment by MoonshineSG** [comment]
if that still doesnt work, send me a full gcode file so i can do some tests...

**Comment by turuncuoglu** [comment]
Thanks for the quick response.  I was able to inject the code with modifications.  The printer pauses but it is at the beginning of the layer.  Is there a way to pause the printer move it out of the way and return when the print is resumed?

[xyzCalibration_cube_multi.zip](https://github.com/MoonshineSG/OctoPrint-MultiColors/files/3144428/xyzCalibration_cube_multi.zip)

**Comment by MoonshineSG** [comment]
The injected code is customisable as well... :)

**Comment by turuncuoglu** [comment]
Yes right after I wrote that I realize that the code is customizable.  I will see if can figure it out.  Thanks for your help and great plug in.
