### ISSUE TITLE
Not injecting g-code Issue.

### ISSUE THREAD

**Issue by mstein792** [MoonshineSG/OctoPrint-MultiColors#38]
I am having the issue of it failing to inject. I am using S3D and the expression used in my gcode is "; layer 13, Z = 2.660" and in the plugin I am putting "; layer {layer}" I have tried most fixes i've found and no dice...  any ideas?

**Comment by MoonshineSG** [comment]
send a sample of your file and i'll have a look

**Comment by MoonshineSG** [comment]
Btw, I'm using S3D and my - working - regex is `;LAYER:{layer}`

**Comment by mstein792** [comment]
[30 doneee.zip](https://github.com/MoonshineSG/OctoPrint-MultiColors/files/3357722/30.doneee.zip)
here ya go, thanks!!

**Comment by mstein792** [comment]
also, tried the one you posted and no dice.  Just to make sure i'm doing this right... I upload to octoprint, choose the file, then go to multicolor and just input layer number and correct regex, right?!?

**Comment by MoonshineSG** [comment]
try `; layer {layer}.*`

**Comment by mstein792** [comment]
Worked perfect!! Thank you!
