### ISSUE TITLE
Check if injected is present

### ISSUE THREAD

**Issue by temuccio** [MoonshineSG/OctoPrint-MultiColors#4]
Hello, 
how I check if the injected change filament at layer xx is correctly present?
If I download the file and open it with text read, I can see it?
I have try but doesn't works. I need to check if the pause is present because the file are worked from many peaple.
Thanks a lot.

**Comment by MoonshineSG** [comment]
Can you post the setting you use ? The GCODE and the REGEX ?

**Comment by temuccio** [comment]
Hello @MoonshineSG ,
this is the GCODE:

```
G28 X Y
M117 Change filament
M0
```

and this is the REGEX:
`layer {layer},.*?`

**Comment by MoonshineSG** [comment]
and inside your code there are lines that match `layer {layer},.*?` ?

**Comment by temuccio** [comment]
After download the file from octoprint I don't have any line that match with `layer {layer},.*?`

**Comment by MoonshineSG** [comment]
no... before that....

**Comment by temuccio** [comment]
Where I check it without download the gcode?

**Comment by MoonshineSG** [comment]
hmmm... you need to make sure the regex will match the line in the slicer generated gcode. you need to do this once, and if you don't change the slicer, you probably wont need to touch it again.

**Comment by temuccio** [comment]
ok, but how I check if the injection are effect?

**Comment by MoonshineSG** [comment]
there are 2 way. download the gcode (after you run the replacement) and check the lines ,or view it in octoprint and you will see the "pause" (head moves to 0,0) at the selected layer
