### ISSUE TITLE
Extra Pauses from Regex. Regex needs "\n"?

### ISSUE THREAD

**Issue by brianhrowe** [MoonshineSG/OctoPrint-MultiColors#42]
I set up the multi color plugin and tested it with a small 20mm XYZ cube. It seemed to work well after I updated the Regex to look for Cura 4.4's layer comments.

I then used it for a larger model and ran into the issue that it kept pausing unexpectedly ~10 times extra. I realized that having targeted line 13 it was pausing at 13 then 130, 131, 132 through to 139 as well.

I opened the GCode file and searched for '; multi color' and found there were in fact 11 instances of it at the aforementioned layers.

I popped into regex101.com to test some things and sure enough it found every instance of ";LAYER:13" even those followed by another digit.

The only thing I've found to alleviate this is to add a "\n" at the end Regex so it doesn't find other instances.

Screenshots:
![image](https://user-images.githubusercontent.com/2099182/72206767-bc112880-345f-11ea-8187-f7d426a567e3.png)

![image](https://user-images.githubusercontent.com/2099182/72206760-a3a10e00-345f-11ea-95a2-5b96010be5cf.png)

![image](https://user-images.githubusercontent.com/2099182/72206816-3fcb1500-3460-11ea-83ab-d05643f48d19.png)

![image](https://user-images.githubusercontent.com/2099182/72206828-4f4a5e00-3460-11ea-8d95-7cae4d2e9c1d.png)

**Comment by MoonshineSG** [comment]
you don't need `.*?` at the end of the regex... So for your case it would be `;LAYER:{layer}`

In the example given by me, there's is a `,` after `{layer}` and the `.*?` would catch any other words the slicer inserts after the layer number as, for example, in Simplify3D which writes: `; layer 1, Z = 0.300`

Note: the plugin automatically concats a `(\r\n?|\n)` after the regex to catch the "end of line" (for multiple platforms)
