### ISSUE TITLE
Hardcoded path in python file __init__.py

### ISSUE THREAD

**Issue by nothing-fr** [MoonshineSG/OctoPrint-MultiColors#5]
You use hardcoded path "/home/pi/.octoprint/uploads/" in the "**init**.py" file, I'm not using octopi so i have to change it.

`ret = self.inject_gcode(os.path.join("/home/pi/.octoprint/uploads/", data.get('file')), data.get('layers').replace(",", " ").split(), data.get('find_string'), data.get('gcode'))
`

Can you make it changeable via a plugin configuration page ?

**Comment by MoonshineSG** [comment]
sure, I'll try ...

can you tell me what does your folder is ? what OS are you using ?

**Comment by MoonshineSG** [comment]
see [https://github.com/MoonshineSG/OctoPrint-MultiColors/releases/tag/1.0.3]

**Comment by nothing-fr** [comment]
I'm using Octoprint on my Synology NAS. ( https://synocommunity.com/package/octoprint )

My folder for uploads is : `/volume1/octoprint/uploads`

**Comment by MoonshineSG** [comment]
see if the 1.0.3 works for you

**Comment by MoonshineSG** [comment]
1.0.4 is a better implementation ... let me know if it works for you ....

**Comment by MoonshineSG** [comment]
@nothing-fr did you managed to run the latest version ?

**Comment by nothing-fr** [comment]
Sorry I was not here this weekend, i'll try it today if i have time, thanks.

**Comment by MoonshineSG** [comment]
no worries... was just curious if it works for you (it should :D )
