### ISSUE TITLE
Doesn't work with folders

### ISSUE THREAD

**Issue by heathicus** [MoonshineSG/OctoPrint-MultiColors#8]
I'm using the dev branch of Octoprint which supports organizing files in folders.  The MultiColor plugin only works on files in the root of the storage.  It fails when using a file in any folder below that.

**Comment by MoonshineSG** [comment]
Yes, that is right. For now. Mostly because I don't use folders. Can't really see the use for them.
But if there seams to be a use for it, I'll look into it. Give me a few days...

**Comment by heathicus** [comment]
I have a lot of different files for different projects that I print repeatedly and I use folders to keep things organized.  The MultiColor plugin is my favorite way to inject the pause code when doing multiple color changes.  It's sort of a pain to upload the file to the root, perform the injection, download the file, delete it from the root, then re-upload it to the proper folder.  First world problems, I know, but if the MultiColor plugin could support folders, it would save me a lot of time.

**Comment by MoonshineSG** [comment]
as it turns out, it's a super easy fix... enjoy!

**Comment by synman** [comment]
thank you so much for fixing this... I stumbled upon it a couple weeks ago and have been moving stuff back into the ~/ ever since.  No longer!

Thanks again!

Shell

**Comment by heathicus** [comment]
Thanks so much for the quick update!!
