### ISSUE TITLE
Any idea if this script is compatible with latest Cura?

### ISSUE THREAD

**Issue by valid8riam** [MoonshineSG/OctoPrint-MultiColors#9]

**Comment by MoonshineSG** [comment]
it should be. If set properly, the regular expression (regex) will match whatever the slicers sets as a layer identifier.

**Comment by valid8riam** [comment]
Thanks for your reply.  I'm sorry that I don't know anything about what you mean by "regular expression", but what I can report is that when I drop the .py script into my ...\PostProcessing\scripts folder (where I find the three default supported PostProcessing Cura scripts), suddenly I find that those three previously working scripts no longer are 'available' for use at all and I can't find your script to use/try either.  It seems (to me) that by simply placing your .py script into the folder it 'breaks' the ...\PostProcessing scripts that come installed by default with Cura.

Any thoughts?  Thanks again for taking the time to respond.

**Comment by MoonshineSG** [comment]
Oh.... I think you might be confusing Cura PostProcessing scripts with OctoPrint plugins... The only similarity is that both are python scripts. 

`OctoPrint-MultiColors` is an OctoPrint plugin meant to be installed under an OctoPrint instance and used on gcode files that have already been generated by a slicer and uploaded to OctoPrint. 

It didn't (and never will) work on any version of Cura, new or old...

Hope this helps. Well... at least it explains why it doesn't work in Cura.

**Comment by valid8riam** [comment]
Yes, you are clearly correct.  Thank you then again for taking the time to teach me a few new things!

Take care.
